[build]
# Specify the Python versions to build wheels for
# Use "*" to include all available Python versions
# Use "cpXX" to target a specific major Python version (e.g., "cp36" for Python 3.6)
# Use "cpXY-win_amd64" for specific Python version and platform (e.g., "cp39-win_amd64")
# Use "ppYYYY" for PyPy version (e.g., "pp370")
# Use "manylinux_X_Y" for specific manylinux platform (e.g., "manylinux2014_x86_64")
# Use "macos_XX_Y" for specific macOS version (e.g., "macos_10_9")
python_versions = ["3.6", "3.7", "3.8", "3.9"]

# Specify the build options for each platform
[build.options]
# Additional environment variables to set during the build process
# Set any required build flags or paths here
# Example: CFLAGS = "-O3"
# Example: LDFLAGS = "-L/path/to/libraries"
# Example: CPPFLAGS = "-I/path/to/headers"
# Example: PATH = "/custom/path:$PATH"
CFLAGS = "-O3"

# Set verbose mode for cibuildwheel
environment = { CIBW_VERBOSE = "1" }

# Additional dependencies to install before building
# Use the package name and optional version specifier
# Example: "numpy" or "numpy~=1.19.0"
dependencies = ["numpy"]

# Additional environment variables to set during testing
# Set any required environment variables for running tests here
# Example: PYTEST_ADDOPTS = "--verbose"
# Example: MPLBACKEND = "Agg"
# Example: CUSTOM_VARIABLE = "value"
PYTEST_ADDOPTS = "--verbose"

# Exclude specific platforms from building
# Uncomment the line below to exclude building for macOS
# platforms = ["macos"]
