[tool.poetry]
name = "gravitas"
version = "0.0.19"
description = "High-fidelity gravity fields for satellite propagation"
authors = ["Liam Robinson <robin502@purdue.edu>"]
readme = "README.md"
packages = [{include = "gravitas"}]
include = [{path = "gravitas", format = "sdist"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: MacOS",
]


[tool.poetry.dependencies]
python = ">=3.5,<3.12"
numpy = "^1.19"

[tool.cibuildwheel.environment]
CIBW_VERBOSE = "1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
    "setuptools>=42",
    "wheel",
    "poetry-core",
    "numpy"
]